- name: Update packages
  yum:
    name: '*'
    state: latest

- name: Add Jenkins repo
  get_url:
    url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo

- name: Import Jenkins key
  ansible.builtin.rpm_key:
    state: present
    key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key

- name: Install Java
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - java-21-amazon-corretto-devel
    - java-17-amazon-corretto-devel
    - java-11-amazon-corretto-devel
  ignore_errors: yes  

- name: Install Jenkins
  yum:
    name: jenkins
    state: latest

- name: Start Jenkins
  ansible.builtin.systemd:
    name: jenkins
    enabled: true
    state: started
