version: "3.9"

services:
  db:
    image: postgres:17
    container_name: mydb
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    image: abdelrahmandevops/devops-app:latest
    container_name: app-server
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    restart: always
    depends_on:
      db:
        condition: service_healthy

  test:
    image: python:3.13-slim
    container_name: app-tests
    depends_on:
      - server
    working_dir: /tests
    volumes:
      - ./tests:/tests
    command: >
      sh -c "
        pip install --no-cache-dir -r requirements.txt &&
        pytest test_api_dashboard.py --maxfail=1 --disable-warnings -q
      "

volumes:
  db-data:
