- name: Add ingress-nginx Helm repo
  community.kubernetes.helm_repository:
    name: ingress-nginx
    repo_url: https://kubernetes.github.io/ingress-nginx

- name: Deploy ingress-nginx controller
  community.kubernetes.helm:
    name: ingress-nginx
    chart_ref: ingress-nginx/ingress-nginx
    release_namespace: ingress-nginx
    create_namespace: true
    values:
      controller:
        replicaCount: 2
        service:
          type: LoadBalancer

- name: Wait for LoadBalancer IP/DNS
  kubernetes.core.k8s_info:
    kind: Service
    namespace: ingress-nginx
    name: ingress-nginx-controller
  register: nginx_svc
  until: nginx_svc.resources[0].status.loadBalancer.ingress is defined
  retries: 10
  delay: 15

- name: Set ingress_host fact
  set_fact:
    ingress_host: "{{ nginx_svc.resources[0].status.loadBalancer.ingress[0].hostname }}"

#- name: Deploy Ingress
#  kubernetes.core.k8s:
#    state: present
#    definition: "{{ lookup('template', 'templates/ingress.yml.j2') }}"
