- name: Add ingress-nginx Helm repo
  community.kubernetes.helm_repository:
    name: ingress-nginx
    repo_url: https://kubernetes.github.io/ingress-nginx
    state: present

- name: Create ingress-nginx namespace
  kubernetes.core.k8s:
    kind: Namespace
    name: ingress-nginx
    state: present

- name: Deploy ingress-nginx controller
  community.kubernetes.helm:
    name: ingress-nginx
    chart_ref: ingress-nginx/ingress-nginx
    release_namespace: ingress-nginx
    chart_version: "4.10.0"  # Specify version for reproducibility
    wait: true  # Wait for resources to be ready
    wait_timeout: 300
    values:
      controller:
        replicaCount: 2
        service:
          type: LoadBalancer
          annotations:
            service.beta.kubernetes.io/aws-load-balancer-type: "nlb"  # Use Network Load Balancer for EKS
            service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
        config:
          use-forwarded-headers: "true"
        metrics:
          enabled: true  # Enable metrics for monitoring
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi

- name: Wait for LoadBalancer to be ready
  kubernetes.core.k8s_info:
    kind: Service
    namespace: ingress-nginx
    name: ingress-nginx-controller
  register: nginx_svc
  until: nginx_svc.resources[0].status.loadBalancer.ingress is defined and nginx_svc.resources[0].status.loadBalancer.ingress | length > 0
  retries: 20  # Increased retries for AWS LB provisioning
  delay: 10

- name: Set ingress_host fact
  set_fact:
    ingress_host: "{{ nginx_svc.resources[0].status.loadBalancer.ingress[0].hostname }}"

- name: Display ingress hostname
  debug:
    msg: "NGINX Ingress Controller is available at: {{ ingress_host }}"