---
- name: Add ingress-nginx Helm repo
  shell: |
    helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
    helm repo update

- name: Create ingress-nginx namespace
  shell: |
    kubectl create namespace ingress-nginx --dry-run=client -o yaml | kubectl apply -f -

- name: Deploy NGINX Ingress Controller
  shell: |
    helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx \
      --namespace ingress-nginx \
      --version 4.10.0 \
      --set controller.replicaCount=2 \
      --set controller.service.type=LoadBalancer \
      --wait

- name: Wait for LoadBalancer to be ready
  shell: |
    kubectl -n ingress-nginx get service ingress-nginx-controller \
      -o jsonpath='{.status.loadBalancer.ingress[0].hostname}'
  register: nginx_lb_hostname
  until: nginx_lb_hostname.stdout != ''
  retries: 20
  delay: 10

- name: Display ingress hostname
  debug:
    msg: "NGINX Ingress Controller is available at: {{ nginx_lb_hostname.stdout }}"
