# roles/k8s/tasks/main.yml
---
- name: Render Helm values for App
  template:
    src: "/home/ec2-user/helm/app-chart/values-{{ deploy_env }}.yaml.j2"
    dest: "/home/ec2-user/helm/app-chart/values-{{ deploy_env }}.yaml"

- name: Render Helm values for Postgres
  template:
    src: "/home/ec2-user/helm/postgres-chart/values-{{ deploy_env }}.yaml.j2"
    dest: "/home/ec2-user/helm/postgres-chart/values-{{ deploy_env }}.yaml"

- name: Deploy App Helm Chart
  community.kubernetes.helm:
    release_name: "app-{{ deploy_env }}"
    chart_ref: /home/ec2-user/helm/app-chart
    release_namespace: "{{ namespace }}"
    values_files:
      - "/home/ec2-user/helm/app-chart/values-{{ deploy_env }}.yaml"
    create_namespace: yes
    release_state: present

- name: Deploy Postgres Helm Chart
  community.kubernetes.helm:
    release_name: "postgres-{{ deploy_env }}"
    chart_ref: /home/ec2-user/helm/postgres-chart
    release_namespace: "{{ namespace }}"
    values_files:
      - "/home/ec2-user/helm/postgres-chart/values-{{ deploy_env }}.yaml"
    create_namespace: yes
    release_state: present

- name: Rolling restart App deployments
  command: kubectl rollout restart deployment {{ item }} -n "{{ namespace }}"
  loop:
    - backend
    - frontend

