# App Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: "{{ .Values.nginxLBHost }}"
      http:
        paths:
          - path: /app
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
          - path: /app/api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 8080


