# Application Secrets
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend-secret
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: "{{ .Values.postgresConfig.user }}"
  SPRING_DATASOURCE_PASSWORD: "{{ .Values.postgresConfig.password }}"
