# Application ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMapName }}
  namespace: {{ .Values.namespace }}
data:
  APP_ENV: "production"
  APP_PORT: "8080"
  SPRING_PROFILES_ACTIVE: "prod"