# /home/ec2-user/helm/postgres-chart/Chart.yaml
apiVersion: v2
name: postgres-chart   # change from "helm" to "postgres-chart"
description: A Helm chart for Postgres
type: application
version: 0.1.0
appVersion: "1.16.0"
