# playbooks/deploy-app.yml
- name: Deploy Backend, Frontend, and Postgres on EKS
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - ../vars/main.yml
    - ../vars/terraform-generated.yml

  pre_tasks:
    - name: Ensure required Python packages are installed
      pip:
        name:
          - kubernetes
          - boto3
          - botocore
        executable: pip3  

  roles:
    - k8s
