---
- name: Install Jenkins plugins
  hosts: jenkins-server
  become: yes

  vars_files:
    - ../vars/secrets.yml   # for jenkins_admin_user / jenkins_admin_pass

  tasks:
    - name: Install required plugins
      community.general.jenkins_plugin:
        name: "{{ item }}"
        state: present
        url: "http://localhost:8080"
        url_username: "{{ jenkins_admin_user }}"
        url_password: "{{ jenkins_admin_pass }}"
      loop: "{{ jenkins_plugins }}"

    - name: Restart Jenkins after plugins are installed
      ansible.builtin.service:
        name: jenkins
        state: restarted
